# This is a simple number guessing game in which the input number entered by the player is matched with the random number generated by computer.
# Here total 9 chances are given to the player to guess the number and if they enter incorrect number it tells the total attempts left.

import random
print("----------Welcome to Number Guessing game developed by Arpit Patel----------")
print("You have only 9 attempts to guess the correct number!")

random_number = random.randint(1,50) # Generates random numbers between 1 to 50
no_of_chances = 1 # Initialize chance given to player to 1

while(True):

    # Taking input from player
    player_input = int(input("\nGuess any number between 1 to 50: "))


    if no_of_chances == 9 and player_input == random_number:
        print(f"\n Whoo Whoo, its your day buddy!!! you finally guessed correctly on your last attempt")
        break

    elif no_of_chances == 9:
        print(f"\n game over!!!!!,{no_of_chances} attempts are finish, better luck next time ")
        break

    elif player_input < random_number:
        print("Your guess was too low: Guess a number higher than", player_input)
        print(f"{9 - no_of_chances} attemps left")
        print("Please try again")
        no_of_chances = no_of_chances + 1

    elif player_input > random_number:
        print("Your guess was too high: Guess a number lower than", player_input)
        print(f"{9 - no_of_chances} attempts left")
        print("Please try again")
        no_of_chances = no_of_chances + 1

    elif player_input == random_number:
        print(f"\n Congratulations you won, you took {no_of_chances} attempts.")
        break

    else:
        print("Something went wrong...")




